# Generated by Django 3.0.4 on 2020-03-25 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('lede', models.CharField(blank=True, help_text='A short summary of your review', max_length=100)),
                ('body', models.TextField(max_length=500)),
                ('rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='places.Place')),
            ],
        ),
    ]
